### ISSUE TITLE
Posting High scores using GET URLs

### ISSUE THREAD

**Issue by axemclion** [mkagenius/mkagenius.github.io#1]
Looks like high score inputs are done using GET. Consider moving it to POST since GET has a max limit of number of characters, so techincally if I am super fast, GET will truncate a part of my userInputs. 

Test case - run this  `var timer = window.setInterval(function(){parseInt($('#ltext').text()) > parseInt($('#rtext').text()) ? rightPressed() : leftPressed();},1);window.setTimeout(function(){window.clearInterval(timer)},60000)` - score is not submitted.

**Comment by mkagenius** [comment]
Ah!
I also worried about that. Thought maybe human cannot do lot of inputs in 60 seconds.

How many inputs do you think a human can do in 60 seconds? I can then test with dummy GET request for that many inputs.

**Comment by axemclion** [comment]
The server is also not CORs enabled.

**Comment by mkagenius** [comment]
actually, only GET is supported for now on the server side, for that i have added the CORS :)

**Comment by axemclion** [comment]
I get this  

`
XMLHttpRequest cannot load http://128.199.78.95:8899/sendGame?data=L-2,R-2,L-4,R-2,R-4,L-4,R-2,L-4,R-8…-4,L-4,R-4,L-8,R-8,L-2,L-2,R-4,L-8,R-4,R-4,L-2,L-2,R-8,L-4,L-8,R-2,L-4,L-2. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mkagenius.github.io' is therefore not allowed access. The response had HTTP status code 400.
`

**Comment by axemclion** [comment]
My bad, this was again due to GET URL size.
